{{- $global := fromJson (include "eric-adp-gui-aggregator-service.global" .) -}}
{{- $ingressPath := include "eric-adp-gui-aggregator-service.ingressPath" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-adp-gui-aggregator-service.name" . }}-configmap
  labels:
    {{- include "eric-adp-gui-aggregator-service.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-adp-gui-aggregator-service.annotations" . | nindent 4 }}
data:
  backend-service-config.json: |
    {
        "k8sLabelValue":  "{{ .Values.configuration.k8sLabelValue }}",
        "logging": {
          "enabled": {{ .Values.configuration.logging.enabled }},
          "defaultLogLevel": "{{ .Values.configuration.logging.defaultLogLevel }}",
          "logLevelCategories": {{ .Values.configuration.logging.logLevelCategories | toJson }},
          "serviceName": "{{ .Values.configuration.logging.serviceName }}",
          "stdout": {
            "enabled": {{ include "eric-adp-gui-aggregator-service.stdoutLogEnabled" . }}
          },
          "syslog": {
            "enabled": {{ include "eric-adp-gui-aggregator-service.syslogEnabled" . }},
            "syslogHost": "{{ .Values.configuration.logging.syslog.syslogHost }}",
            "syslogFacility": "{{ .Values.configuration.logging.syslog.syslogFacility }}"
          }
        },
        "faultIndications": {
          "enabled": {{ .Values.configuration.faultIndications.enabled }}
        },
        "discoverIngress": {{ .Values.configuration.discoverIngress }},
        "ingressPath": "{{ $ingressPath }}",
        "useHttps": {{ $global.security.tls.enabled }},
        "verifyClientCertificate": "{{ .Values.service.endpoints.http.tls.verifyClientCertificate }}",
        "enforcedTLS": "{{ .Values.service.endpoints.http.tls.enforced }}",
        "serviceName": "{{ include "eric-adp-gui-aggregator-service.name" . }}",
        "headlessServiceName": "{{ include "eric-adp-gui-aggregator-service.name" . }}-headless-svc",
        "servicePort": "{{ .Values.service.port }}",
        "dependencies": {
          "logtransformer": {
            "enabled": {{ include "eric-adp-gui-aggregator-service.syslogEnabled" . }}
          },
          "prometheus": {
            "enabled": {{ .Values.metrics.enabled }},
            "appName": "{{ .Values.configuration.dependencies.prometheus.appName }}"
          },
          "faultHandler": {
            "enabled": {{ .Values.configuration.faultIndications.enabled }},
            "hostname": "{{ .Values.configuration.dependencies.faultHandler.hostname }}",
            "tlsPort": {{ .Values.configuration.dependencies.faultHandler.tlsPort }},
            "httpPort": {{ .Values.configuration.dependencies.faultHandler.httpPort }},
            "serviceName": "{{ .Values.configuration.dependencies.faultHandler.serviceName }}"
          }
        }

    }

  manualconfig.json: |
     {
        "apps": [
        {{- if .Values.manualconfig.apps | empty | not }}{{ $appsLength := len .Values.manualconfig.apps | add -1 }}
        {{- range $index, $value := .Values.manualconfig.apps }}
          {
            {{- if $value.type }}
            "type": {{ $value.type | quote }},
            {{- end }}
            {{- if $value.descriptionShort }}
            "descriptionShort": {{ $value.descriptionShort | quote }},
            {{- end }}
            {{- if $value.descriptionLong }}
            "descriptionLong": {{ $value.descriptionLong | quote }},
            {{- end }}
            {{- if $value.childNames }}
            "childNames": [{{ $childNamesLength := len $value.childNames | add -1 }}
              {{- range $childNameIndex, $childName := $value.childNames }}
              {{ $childName | quote }}{{- if lt $childNameIndex $childNamesLength }},{{- end }}
              {{- end }}
            ],
            {{- end }}
            {{- if $value.groupNames }}
            "groupNames": [{{ $groupNamesLength := len $value.groupNames | add -1 }}
              {{- range $groupNameIndex, $groupName := $value.groupNames }}
              {{ $groupName | quote }}{{- if lt $groupNameIndex $groupNamesLength }},{{- end }}
              {{- end }}
            ],
            {{- end }}
            {{- if $value.tags }}
            "tags": [{{ $tagsLength := len $value.tags | add -1 }}
              {{- range $tagsIndex, $tag := $value.tags }}
              {{ $tag | quote }}{{- if lt $tagsIndex $tagsLength }},{{- end }}
              {{- end }}
            ],
            {{- end }}
            {{- if $value.priority }}
            "priority": {{ $value.priority }},
            {{- end }}
            {{- if $value.color }}
            "color": {{ $value.color | quote }},
            {{- end }}
            {{- if $value.acronym }}
            "acronym": {{ $value.acronym | quote }},
            {{- end }}
            {{- if $value.url }}
            "url": {{ $value.url | quote }},
            {{- end }}
            {{- if $value.route }}
            "route": {{ $value.route | quote }},
            {{- end }}
            {{- if $value.hidden }}
            "hidden": {{ $value.hidden | quote }},
            {{- end }}
            "displayName": {{ $value.displayName | quote }},
            "version": {{ $value.version | quote }},
            "name": {{ $value.name | quote }}
          }{{- if lt $index $appsLength }},{{- end }}
        {{- end }}{{ else }}{{- end }}
        ],
        "groups": [
        {{- if .Values.manualconfig.groups | empty | not }}{{ $groupsLength := len .Values.manualconfig.groups | add -1 }}
        {{- range $index, $value := .Values.manualconfig.groups }}
          {
            {{- if $value.descriptionShort }}
            "descriptionShort": {{ $value.descriptionShort | quote }},
            {{- end }}
            {{- if $value.descriptionLong }}
            "descriptionLong": {{ $value.descriptionLong | quote }},
            {{- end }}
            {{- if $value.type }}
            "type": {{ $value.type | quote }},
            {{- end }}
            {{- if $value.priority }}
            "priority": {{ $value.priority }},
            {{- end }}
            {{- if $value.tags }}
            "tags": [{{ $tagsLength := len $value.tags | add -1 }}
              {{- range $tagsIndex, $tag := $value.tags }}
              {{ $tag | quote }}{{- if lt $tagsIndex $tagsLength }},{{- end }}
              {{- end }}
            ],
            {{- end }}
            {{- if $value.color }}
            "color": {{ $value.color | quote }},
            {{- end }}
            {{- if $value.acronym }}
            "acronym": {{ $value.acronym | quote }},
            {{- end }}
            "displayName": {{ $value.displayName | quote }},
            "version": {{ $value.version | quote }},
            "name": {{ $value.name | quote }}
          }{{- if lt $index $groupsLength }},{{- end }}
        {{- end }}{{ else }}{{- end }}
        ]
      }
  manual-overrides.json: |
     {
        "overrides": {
          "apps": [
          {{- if .Values.manualconfig.overrides.apps | empty | not }}{{ $appsLength := len .Values.manualconfig.overrides.apps | add -1 }}
          {{- range $index, $value := .Values.manualconfig.overrides.apps }}
            {
              {{- if $value.type }}
              "type": {{ $value.type | quote }},
              {{- end }}
              {{- if $value.descriptionShort }}
              "descriptionShort": {{ $value.descriptionShort | quote }},
              {{- end }}
              {{- if $value.descriptionLong }}
              "descriptionLong": {{ $value.descriptionLong | quote }},
              {{- end }}
              {{- if $value.childNames }}
              "childNames": [{{ $childNamesLength := len $value.childNames | add -1 }}
                {{- range $childNameIndex, $childName := $value.childNames }}
                {{ $childName | quote }}{{- if lt $childNameIndex $childNamesLength }},{{- end }}
                {{- end }}
              ],
              {{- end }}
              {{- if $value.groupNames }}
              "groupNames": [{{ $groupNamesLength := len $value.groupNames | add -1 }}
                {{- range $groupNameIndex, $groupName := $value.groupNames }}
                {{ $groupName | quote }}{{- if lt $groupNameIndex $groupNamesLength }},{{- end }}
                {{- end }}
              ],
              {{- end }}
              {{- if $value.tags }}
              "tags": [{{ $tagsLength := len $value.tags | add -1 }}
                {{- range $tagsIndex, $tag := $value.tags }}
                {{ $tag | quote }}{{- if lt $tagsIndex $tagsLength }},{{- end }}
                {{- end }}
              ],
              {{- end }}
              {{- if $value.priority }}
              "priority": {{ $value.priority }},
              {{- end }}
              {{- if $value.color }}
              "color": {{ $value.color | quote }},
              {{- end }}
              {{- if $value.acronym }}
              "acronym": {{ $value.acronym | quote }},
              {{- end }}
              {{- if $value.url }}
              "url": {{ $value.url | quote }},
              {{- end }}
              {{- if $value.route }}
              "route": {{ $value.route | quote }},
              {{- end }}
              {{- if $value.displayName }}
              "displayName": {{ $value.displayName | quote }},
              {{- end }}
              {{- if $value.version }}
              "version": {{ $value.version | quote }},
              {{- end }}
              {{- if $value.hidden }}
              "hidden": {{ $value.hidden | quote }},
              {{- end }}
              "name": {{ $value.name | quote }}
            }{{- if lt $index $appsLength }},{{- end }}
          {{- end }}{{ else }}{{- end }}
          ],
          "groups": [
          {{- if .Values.manualconfig.overrides.groups | empty | not }}{{ $groupsLength := len .Values.manualconfig.overrides.groups | add -1 }}
          {{- range $index, $value := .Values.manualconfig.overrides.groups }}
            {
              {{- if $value.descriptionShort }}
              "descriptionShort": {{ $value.descriptionShort | quote }},
              {{- end }}
              {{- if $value.descriptionLong }}
              "descriptionLong": {{ $value.descriptionLong | quote }},
              {{- end }}
              {{- if $value.type }}
              "type": {{ $value.type | quote }},
              {{- end }}
              {{- if $value.priority }}
              "priority": {{ $value.priority }},
              {{- end }}
              {{- if $value.tags }}
              "tags": [{{ $tagsLength := len $value.tags | add -1 }}
                {{- range $tagsIndex, $tag := $value.tags }}
                {{ $tag | quote }}{{- if lt $tagsIndex $tagsLength }},{{- end }}
                {{- end }}
              ],
              {{- end }}
              {{- if $value.color }}
              "color": {{ $value.color | quote }},
              {{- end }}
              {{- if $value.acronym }}
              "acronym": {{ $value.acronym | quote }},
              {{- end }}
              {{- if $value.hidden }}
              "hidden": {{ $value.hidden | quote }}
              {{- end }}
              {{- if $value.displayName }}
              "displayName": {{ $value.displayName | quote }},
              {{- end }}
              {{- if $value.version }}
              "version": {{ $value.version | quote }},
              {{- end }}
              "name": {{ $value.name | quote }}
            }{{- if lt $index $groupsLength }},{{- end }}
          {{- end }}{{ else }}{{- end }}
          ],
          "components": [
          {{- if .Values.manualconfig.overrides.components | empty | not }}{{ $componentsLength := len .Values.manualconfig.overrides.components | add -1 }}
          {{- range $index, $value := .Values.manualconfig.overrides.components }}
            {
              {{- if $value.descriptionShort }}
              "descriptionShort": {{ $value.descriptionShort | quote }},
              {{- end }}
              {{- if $value.descriptionLong }}
              "descriptionLong": {{ $value.descriptionLong | quote }},
              {{- end }}
              {{- if $value.type }}
              "type": {{ $value.type | quote }},
              {{- end }}
              {{- if $value.module }}
              "module": {{ $value.module | quote }},
              {{- end }}
              {{- if $value.specification }}
              "specification": {{ $value.specification | quote }},
              {{- end }}
              {{- if $value.service }}
              "service": {{ $value.service | quote }},
              {{- end }}
              {{- if $value.options }}
              "options": {{ $value.options | quote }},
              {{- end }}
              {{- if $value.priority }}
              "priority": {{ $value.priority }},
              {{- end }}
              {{- if $value.tags }}
              "tags": [{{ $tagsLength := len $value.tags | add -1 }}
                {{- range $tagsIndex, $tag := $value.tags }}
                {{ $tag | quote }}{{- if lt $tagsIndex $tagsLength }},{{- end }}
                {{- end }}
              ],
              {{- end }}
              {{- if $value.color }}
              "color": {{ $value.color | quote }},
              {{- end }}
              {{- if $value.acronym }}
              "acronym": {{ $value.acronym | quote }},
              {{- end }}
              {{- if $value.displayName }}
              "displayName": {{ $value.displayName | quote }},
              {{- end }}
              {{- if $value.version }}
              "version": {{ $value.version | quote }},
              {{- end }}
              "name": {{ $value.name | quote }}
            }{{- if lt $index $componentsLength }},{{- end }}
          {{- end }}{{ else }}{{- end }}
          ]
        },
        "groupMappings": [
        {{- if .Values.manualconfig.groupMappings | empty | not }}{{ $groupMappingLength := len .Values.manualconfig.groupMappings | add -1 }}
        {{- range $index, $value := .Values.manualconfig.groupMappings }}
          {
            "group": {{ $value.group | quote }},
            "apps": [{{ $appsLength := len $value.apps | add -1 }}
              {{- range $appsIndex, $app := $value.apps }}
              {{ $app | quote }}{{- if lt $appsIndex $appsLength }},{{- end }}
              {{- end }}
            ]
          }{{- if lt $index $groupMappingLength }},{{- end }}
        {{- end }}{{ else }}{{- end }}
        ]
      }
  manual-service-config.json: |
    {
      "serviceList": [
        {
          "name": {{ include "eric-adp-gui-aggregator-service.name" . | quote}},
          "version": {{ include "eric-adp-gui-aggregator-service.version" . | quote}},
          "URL":
            {{- if $global.security.tls.enabled -}}"https://localhost:{{- .Values.service.port -}}/ui"
            {{- else -}}"http://localhost:{{- .Values.service.port -}}/ui"
            {{- end -}}
        }{{- if .Values.manualconfig.services | empty | not }},{{ end }}
      {{- if .Values.manualconfig.services | empty | not }}{{ $groupsLength := len .Values.manualconfig.services | add -1 }}
      {{- range $index, $value := .Values.manualconfig.services }}
        {
          "name": {{ $value.name | quote }},
          "version": {{ $value.version | quote }},
          "URL": {{ $value.URL | quote }}
        }{{- if lt $index $groupsLength }},{{- end }}
      {{- end }}{{ else }}{{- end }}
      ]
    }
