openapi: 3.0.1
info:
  title: Graphical User Interface Domain Package Config File Descriptor
  description: |
    ```
      Ericsson   |   DocNo <DOC NUMBER>   |   Rev PA1   |   Interwork Description
    ```
    ## Introduction
    This document describes the GUI User Interface Domain Package config file descriptor identified in the ADP GUI FA.
    ### Terms
    - **Package**: A reusable, shared package exposed by a Micro-service. A package contains at least one ES module, and can contain additional static assets (CSS, images, etc.).
    - **ES Module (ESM)**: Part of a package, this is the atomic entity which is loaded by the browser. ES module specification is based on W3C standards.
  version: "1.0.0-alpha"
servers:
  - url: /
    description: Base
tags:
  - name: GUI.DOMAIN.PACKAGE
    x-displayName: Package Config File Descriptor
paths:
  /config.package.json:
    get:
      summary: Fetch package metadata (config.package.json)
      description: |
        File descriptor for shared packages provided by the service.
        This file includes meta information for the shared packages which contains ES modules suitable for modern Micro-frontends.

        This file **MUST** be named as `config.package.json` and **MUST** be accessible from the service root context path.

        Design guidelines for shared packages:
        - A package **MUST** be contained in its own folder.
        - A package **MUST** contain at least one main module, but **MAY** contain multiple sub-modules.
        - Static assets **MUST** be bundled into the package's folder.
      tags:
        - GUI.DOMAIN.PACKAGE
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: ../schemas/ui.config.package.yaml
