ingress:
  enabled: true
  useContour: true
  hostname:
  path:
  ingressClass: EEA-Applications
  adpIccrServiceName: eric-eea-ingress-ctrl-common

log:
  streamingMethod: indirect

configuration:
  faultIndications:
    enabled: false

metrics:
  enabled: false
