demo-ui-service-ecm:
  enabled: true

demo-ui-service-eea:
  enabled: true

demo-ui-service-enm:
  enabled: true

demo-ui-service-esma:
  enabled: true

demo-ui-service-esmb:
  enabled: true

demo-ui-service-esmc:
  enabled: true

demo-ui-service-eui1:
  enabled: true

demo-ui-service-eui2:
  enabled: true

demo-ui-service-3pp:
  enabled: true

eric-oss-help-aggregator:
  enabled: true

help-center-mock-eea:
  enabled: true

help-center-mock-eea-real-doc:
  enabled: true

help-center-mock-ecm:
  enabled: true
