# Global settings
global:
  # log:
  #   streamingMethod: "direct" # can be overridden by 'log.streamingMethod'
  #   outputs: # Used by the APO2 Sidecar
  #     - "applicationLevel"
  #     - "k8sLevel"
  # security:
  #   tls:
  #     enabled: true
  #   policyBinding:
  #     create: false
  #   policyReferenceMap:
  #     default-restricted-security-policy: customer-z-restricted
  # registry:
  #   repoPath:
  #   url: armdocker.rnd.ericsson.se # see default in eric-product-info.yaml
  # nodeSelector: {}
  # pullSecret:
  # timezone: UTC

# Generic Service settings enforced by Desing Rules
annotations: {}

labels: {}

nodeSelector: {}

podDisruptionBudget:
  minAvailable: 1

affinity:
  podAntiAffinity: "soft"

terminationGracePeriodSeconds: 30

tolerations: []

topologySpreadConstraints: []

log:
  streamingMethod:

# Ingress configuration
ingress:
  enabled: false
  useContour: false
  path: /
  hostname:
  ingressClass:
  adpIccrCaSecret:
  adpIccrServiceName: eric-tm-ingress-controller-cr
  tls:
    passthrough: false
    enabled: true
    existingSecret:
  certificates:
    asymmetricKeyCertificateName: gas-http-server

networkPolicy:
  enabled: true

productInfo:
  rstate: RSTATE

imageCredentials:
  repoPath: # overrides repoPath from eric-product-info.yaml
  main:
    repoPath: # see default in eric-product-info.yaml
    registry:
      url: # see default in eric-product-info.yaml
  # secret must be manually created in the namespace, no default value
  #pullSecret:

# Performance Monitoring
metrics:
  enabled: true

# Service config
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  endpoints:
    http:
      tls:
        # Currently it is not supported to use https without enforcing it.
        enforced: required
        # Global TLS must be enabled if this is set to required.
        verifyClientCertificate: required

# Deployment options
replicaCount: 2

# Using RollingUpdate, specify the update strategy for statefulset
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

# Dimensioning + auth resources
resources:
  main:
    limits:
      cpu: 500m
      memory: 300Mi
      ephemeral-storage: "100Mi"
    requests:
      cpu: 250m
      memory: 300Mi
      ephemeral-storage: "100Mi"
  ericsecoauthsap:
    requests:
      cpu: "50m"
      memory: "130Mi"
      ephemeral-storage: "100Mi"
    limits:
      cpu: "50m"
      memory: "130Mi"
      ephemeral-storage: "100Mi"
  ericsecoauthproxy:
    limits:
      cpu: 2000m
      memory: 500Mi
      ephemeral-storage: "100Mi"
    requests:
      cpu: 500m
      memory: 500Mi
      ephemeral-storage: "100Mi"

podPriority:
  main:
    priorityClassName: ""

probes:
  main:
    livenessProbe:
      initialDelaySeconds: 20
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3

# GUI Aggregator Specific configuration
configuration:
  # In case of the authz proxy is disabled,
  # then this parameter could be used to set the whole logout url
  logoutURL:
  # In case of the authz proxy is disabled,
  # then this parameter could be used to set the whole url to the User Account editor
  userAccountURL:
  guiContext: /ui
  k8sLabelValue: workspace-gui
  nodeJsRuntimeReservedMemory: 150
  logging:
    enabled: true
    defaultLogLevel: info
    logLevelCategories:
      requests: info
    serviceName: eric-adp-gui-aggregator-service
    syslog:
      syslogHost: eric-log-transformer
      syslogFacility: local0

  helpAggregator:
    enabled: false
    partOf: workspace-gui
    serviceName: eric-oss-help-aggregator

  faultIndications:
    enabled: false

  cnom:
    defaultDashboards:
      enabled: false

  discoverIngress: false
  dependencies:
    prometheus:
      appName: eric-adp-gas-light
      pmServiceName: eric-pm-server
    faultHandler:
      hostname: eric-fh-alarm-handler
      tlsPort: 6006
      httpPort: 6005
      serviceName: eric-adp-gui-aggregator-service
  siptls:
    rootSecretName: eric-sec-sip-tls-trusted-root-cert

# Portal (UI) specific configs
uiconfig:
  logging:
    logLevel: info
  hostname: # to be filled, if the ingress is not used
  path: # to be filled, if the ingress is not used
  useTls: false # to be filled, if the ingress is not used

# Manual UI Meta and Domain service config
manualconfig:
  apps:
  groups:
  services:
  overrides:
    apps:
    groups:
    components:
  groupMappings:

# Auth Proxy
authorizationProxy:
  enabled: false
  sipoauth2:
    enabled: true
  authnProxyFQDN:
  keycloakFQDN:
  localSpPort: 3000
  adpIamServiceName: eric-sec-access-mgmt
  adpIamServicePort: 8443
  adpIamRealm: oam
  numOfWebServerWorkers: 10
  adpIamAdminSecret: eric-eea-iam-pg-usersecrets
  localSpClientCertVolumeName: authz-client-cert
  # In case of own ICCR and mTLS, overwrite this:
  adpIccrServiceName: eric-tm-ingress-controller-cr
  protectedPaths:
    - /ui
    - /ui-meta
    - /ui-serve
    - /ui-logging
    - /gas-internal
    - /metrics
  authorizationRules: |
    roles:
    - name: all-in-one-gas
    resources:
    - name: all-in-one-gas
      uris:
      - /**
    permissions:
    - name: all-in-one-permission
      config:
        resources:        ["all-in-one-gas"]
        operations:       ["GET","HEAD","POST","PUT","DELETE","CONNECT","OPTIONS","TRACE"]
        roles:            ["all-in-one-gas"]
